# Generated by Django 4.2.1 on 2023-06-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cliente',
            managers=[
            ],
        ),
    ]
