# Generated by Django 4.2.1 on 2023-06-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_cliente_managers'),
        ('loja', '0002_alter_produtos_autor'),
    ]

    operations = [
    ]
